insert into hotword_count (word, count) values ('草泥马', 15);
insert into hotword_count (word, count) values ('你买单', 14);
insert into hotword_count (word, count) values ('你大爷', 13);
insert into hotword_count (word, count) values ('你洗碗', 12);
insert into hotword_count (word, count) values ('小苹果', 11);
insert into hotword_count (word, count) values ('无节操', 10);
insert into hotword_count (word, count) values ('么么哒', 9);
insert into hotword_count (word, count) values ('高大上', 8);
insert into hotword_count (word, count) values ('德意志', 7);
insert into hotword_count (word, count) values ('萌萌哒', 6);
insert into hotword_count (word, count) values ('穷屌丝', 5);
insert into hotword_count (word, count) values ('阿根廷', 4);
insert into hotword_count (word, count) values ('逗你玩', 3);
insert into hotword_count (word, count) values ('你去死', 2);
insert into hotword_count (word, count) values ('西班牙', 1);
insert into hotword_count (word, count) values ('白富美', 10);
insert into hotword_count (word, count) values ('你爱我', 12);
insert into hotword_count (word, count) values ('你真棒', 11);

insert into robot_info (name, password, highestscore, highestcombo, word) values ('Robot', 'asfdasf4214fasf4576', 0, 0, '草泥马');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Robert', '6wtraewgasgfawfwfasf', 0, 0, '你真棒');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Robby', '36ydhbsdgaew5rt3q4ga', 0, 0, '你爱我');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Gears', 'asfdasf4214fasf4576', 0, 0, '无节操');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Blaze', 'asf53q5gdasgasg', 0, 0, '你洗碗');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('BlueFire', 'asfdasf4214fasf4576', 0, 0, '么么哒');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('YellowBea', '6wtraewgasgfawfwfasf', 0, 0, '屌炸天');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Sulvrr', 'asfdasf4214fasf4576', 0, 0, '白富美');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Obama', '36ydhbsdgaew5rt3q4ga', 0, 0, '穷屌丝');
insert into robot_info (name, password, highestscore, highestcombo, word) values ('Delux', 'asfdasf4214fasf4576', 0, 0, '我好吧');
